{*******************************************************}
{                                                       }
{       Pascal Script Source File                       }
{       Run by RemObjects Pascal Script in CnWizards    }
{                                                       }
{       Generated by CnPack IDE Wizards                 }
{                                                       }
{*******************************************************}

program CnTestSelectBlockScript;

uses
  Windows, Messages, SysUtils, Classes, Graphics, Controls, Forms, Dialogs;

var
  Start: TOTACharPos;
  After: TOTACharPos;
begin
  Start.Line := 25;
  Start.CharIndex := 1;
  After.Line := 28;
  After.CharIndex := 3;

  CnOtaSelectBlock(nil, Start, After);
end.
 
