{*******************************************************}
{                                                       }
{       Pascal Script Source File                       }
{       Run by RemObjects Pascal Script in CnWizards    }
{                                                       }
{       Generated by CnPack IDE Wizards                 }
{                                                       }
{*******************************************************}

program CnTestSetProjOptionValueScript;

uses
  Windows, Messages, SysUtils, Classes, Graphics, Controls, Forms, Dialogs;

var
  Options: IOTAProjectOptions;
begin
  Options := CnOtaGetActiveProjectOptions(nil);
  if Options = nil then
  begin
    ErrorDlg('No Project Options Found.');
    Exit;
  end;

  CnOtaSetProjectOptionValue(Options, 'Build', '1');

  // XE DPK will cause source corrupt. Don't know why.
end.
 
