{*******************************************************}
{                                                       }
{       Pascal Script Source File                       }
{       Run by RemObjects Pascal Script in CnWizards    }
{                                                       }
{       Generated by CnPack IDE Wizards                 }
{                                                       }
{*******************************************************}

program CnTestOptionBugScript;

uses
  Windows, Messages, SysUtils, Classes, Graphics, Controls, Forms, Dialogs;

var
  Options: IOTAProjectOptions;
begin
  Options := CnOtaGetActiveProjectOptions(nil);
  if Options = nil then
  begin
    ErrorDlg('No Project or Options.');
    Exit;
  end;

  Options.SetOptionValue('Build', '1');
  InfoDlg('If Current Project is DPK. Please check the DPK Source for Corruption.');
  // If current Project is dpk under 2009 or above, this statement will cause dpk
  // corrupt. 'requires' -> 'rrequires'. 'contains' -> 'ocontains'. Other keys, too.
  // Reason Unknown.
end.
 
