{*******************************************************}
{                                                       }
{       Pascal Script Source File                       }
{       Run by RemObjects Pascal Script in CnWizards    }
{                                                       }
{       Generated by CnPack IDE Wizards                 }
{                                                       }
{*******************************************************}

program CnTestSelectLinesScript;

uses
  Windows, Messages, SysUtils, Classes, Graphics, Controls, Forms, Dialogs;

begin
  CnOtaMoveAndSelectLines(15, 13, nil);
end.
 
