{*******************************************************}
{                                                       }
{       Pascal Script Source File                       }
{       Run by RemObjects Pascal Script in CnWizards    }
{                                                       }
{       Generated by CnPack IDE Wizards                 }
{                                                       }
{*******************************************************}

program CnTestSytaxHighlightScript;

uses
  Windows, Messages, SysUtils, Classes, Graphics, Controls, Forms, Dialogs;

var
  View: IOTAEditView;
  Buffer: IOTAEditBuffer;
  Options: IOTABufferOptions;
begin
  View := CnOtaGetTopMostEditView(nil);
  if View <> nil then
  begin
    Buffer := View.GetBuffer;
    if Buffer <> nil then
    begin
      Options := Buffer.GetBufferOptions;
      if Options <> nil then
      begin
        Writeln(IntToStr(Integer(Options.GetSyntaxHighlight)));
        Exit;
      end;
    end;
  end;
  Writeln('Something nil!');
end.

