{******************************************************************************}
{                       CnPack For Delphi/C++Builder                           }
{                     中国人自己的开放源码第三方开发包                         }
{                   (C)Copyright 2001-2011 CnPack 开发组                       }
{                   ------------------------------------                       }
{                                                                              }
{            本开发包是开源的自由软件，您可以遵照 CnPack 的发布协议来修        }
{        改和重新发布这一程序。                                                }
{                                                                              }
{            发布这一开发包的目的是希望它有用，但没有任何担保。甚至没有        }
{        适合特定目的而隐含的担保。更详细的情况请参阅 CnPack 发布协议。        }
{                                                                              }
{            您应该已经和开发包一起收到一份 CnPack 发布协议的副本。如果        }
{        还没有，可访问我们的网站：                                            }
{                                                                              }
{            网站地址：http://www.cnpack.org                                   }
{            电子邮件：master@cnpack.org                                       }
{                                                                              }
{******************************************************************************}

{$I CnPack.inc}

{$IFDEF CNWIZARDS_LITE}

{$I CnWizards_Lite.inc}

{$ELSE}

// Wizard: CnFastCodeWizard
{$DEFINE CNWIZARDS_CNFASTCODEWIZARD}

// Wizard: CnAlignSizeWizard
{$DEFINE CNWIZARDS_CNALIGNSIZEWIZARD}

// Wizard: CnMessageBoxWizard
{$DEFINE CNWIZARDS_CNMESSAGEBOXWIZARD}

// Wizard: CnComponentSelector
{$DEFINE CNWIZARDS_CNCOMPONENTSELECTOR}

// Wizard: CnTabOrderWizard
{$DEFINE CNWIZARDS_CNTABORDERWIZARD}

// Wizard: CnDfm6To5Wizard
{$DEFINE CNWIZARDS_CNDFM6TO5WIZARD}

// Wizard: CnBookmarkWizard
{$DEFINE CNWIZARDS_CNBOOKMARKWIZARD}

// Wizard: CnSrcTemplate
{$DEFINE CNWIZARDS_CNSRCTEMPLATE}

// Wizard: CnEditorWizard
{$DEFINE CNWIZARDS_CNEDITORWIZARD}

// Wizard: CnMsdnWizard
{$DEFINE CNWIZARDS_CNMSDNWIZARD}

// Wizard: CnPas2HtmlWizard
{$DEFINE CNWIZARDS_CNPAS2HTMLWIZARD}

// Wizard: CnReplaceWizard
{$DEFINE CNWIZARDS_CNREPLACEWIZARD}

// Wizard: CnSourceDiffWizard
{$DEFINE CNWIZARDS_CNSOURCEDIFFWIZARD}

// Wizard: CnStatWizard
{$DEFINE CNWIZARDS_CNSTATWIZARD}

// Wizard: CnPrefixWizard
{$DEFINE CNWIZARDS_CNPREFIXWIZARD}

// Wizard: CnSrcEditorEnhance
{$DEFINE CNWIZARDS_CNSRCEDITORENHANCE}

// Wizard: CnFormEnhanceWizard
{$DEFINE CNWIZARDS_CNFORMENHANCEWIZARD}

// Wizard: CnPaletteEnhanceWizard
{$DEFINE CNWIZARDS_CNPALETTEENHANCEWIZARD}

// Wizard: CnCorPropWizard
{$DEFINE CNWIZARDS_CNCORPROPWIZARD}

// Wizard: CnProjectExtWizard
{$DEFINE CNWIZARDS_CNPROJECTEXTWIZARD}

// Wizard: CnCommentCropperWizard
{$DEFINE CNWIZARDS_CNCOMMENTCROPPERWIZARD}

// Wizard: CnCpuWinEnhanceWizard
{$DEFINE CNWIZARDS_CNCPUWINENHANCEWIZARD}

// Wizard: CnObjInspectorEnhanceWizard
{$DEFINE CNWIZARDS_CNOBJINSPECTORENHANCEWIZARD}

// Wizard: CnRepositoryMenuWizard
{$DEFINE CNWIZARDS_CNREPOSITORYMENUWIZARD}

// Wizard: CnDUnitWizard
{$DEFINE CNWIZARDS_CNDUNITWIZARD}

// Wizard: CnIniFilerWizard
{$DEFINE CNWIZARDS_CNINIFILERWIZARD}

// Wizard: CnMemProfWizard
{$DEFINE CNWIZARDS_CNMEMPROFWIZARD}

// Wizard: CnExplorerWizard
{$DEFINE CNWIZARDS_CNEXPLORERWIZARD}

// Wizard: CnFilesSnapshotWizard
{$DEFINE CNWIZARDS_CNFILESSNAPSHOTWIZARD}

// Wizard: CnWinTopRoller
{$DEFINE CNWIZARDS_CNWINTOPROLLER}

// Wizard: CnInputHelper
{$DEFINE CNWIZARDS_CNINPUTHELPER}

// Wizard: CnSourceHighlight
{$DEFINE CNWIZARDS_CNSOURCEHIGHLIGHT}

// Wizard: CnProcListWizard
{$DEFINE CNWIZARDS_CNPROCLISTWIZARD}

// Wizard: CnVerEnhanceWizard
{$DEFINE CNWIZARDS_CNVERENHANCEWIZARD}

// Wizard: CnUsesCleaner
{$DEFINE CNWIZARDS_CNUSESCLEANER}

// Wizard: CnIdeEnhanceMenuWizard
{$DEFINE CNWIZARDS_CNIDEENHANCEMENUWIZARD}

// Wizard: CnIdeBRWizard
{$DEFINE CNWIZARDS_CNIDEBRWIZARD}

// Wizard: CnScriptWizard
{$DEFINE CNWIZARDS_CNSCRIPTWIZARD}

// Wizard: CnFeedReaderWizard
{$DEFINE CNWIZARDS_CNFEEDREADERWIZARD}

{$ENDIF}

{$I CnWizards_Def.inc}
