name: Sign Installer with SignPath

on:
  workflow_dispatch:            # 允许手动触发
  # 也可以添加 push: 或 schedule: 触发器

jobs:
  sign-bin-inst:
    runs-on: ubuntu-latest
    permissions:
      actions: read             # 允许读取 artifact 信息
      contents: read

    steps:
      - name: 下载待签名的安装包文件，一个单一 exe
        run: |
          mkdir -p unsigned_artifact
          curl -L "https://download.cnpack.org/Installer.exe" --output "./unsigned_artifact/Installer.exe"
          echo "文件下载完成"
          ls -la ./unsigned_artifact/

      - name: 上传文件为 GitHub Artifact
        uses: actions/upload-artifact@v7
        id: upload-unsigned
        with:
          name: unsigned-bin-zip
          path: ./unsigned_artifact/
          if-no-files-found: error
          # 保持原始 zip 文件不变，不压缩成嵌套 zip
          archive: false

      - name: 提交签名请求到 SignPath
        uses: signpath/github-action-submit-signing-request@v2
        with:
          api-token: ${{ secrets.SIGNPATH_API_TOKEN }}
          organization-id: '3a9625c5-a4a0-46c9-8e46-2f1414ee63b0'
          project-slug: 'cnwizards'
          signing-policy-slug: 'test-signing'
          artifact-configuration-slug: 'sign_single_installer'
          github-artifact-id: ${{ steps.upload-unsigned.outputs.artifact-id }}
          wait-for-completion: true
          # 签名后文件保存目录
          output-artifact-directory: ./signed_artifact

      - name: 显示签名结果
        run: |
          echo "签名完成，签名文件位于："
          ls -la ./signed_artifact/
